image: kissaki/qt5-buildenv:latest

build:
  stage: build
  script:
    - cd src
    - qmake
    - make
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}_${CI_BUILD_REF}"
    paths:
    - src/bin/Videocutter
