name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: dotnet test
      run: dotnet test src --property:Configuration=Release
    - name: publish
      run: dotnet publish src\Videocutter --property:Configuration=Release --os win --arch x64 --output publish
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        path: publish/**
        if-no-files-found: error
    - name: Publish GitHub Release
      if: github.ref_type == 'tag' && startsWith(github.ref_name, 'v')
      run: hub release create --attach publish/Videocutter.exe --attach publish/Videocutter.pdb --message "${{ github.ref_name }}" "${{ github.ref_name }}"
